### ISSUE TITLE
HASelect doesn't work

### ISSUE THREAD

**Issue by netmindz** [dawidchyrzynski/arduino-home-assistant#164] opened 2023-05-04 00:30 UTC
The example select.ino had issues with select being redefined but if swap to selectTest, I then see the device appear in HA, but changes to HA don't call onSelectCommand nor does calling setState actually appear to trigger a change in HA

**Comment by netmindz** [comment] 2023-05-04 01:10
ok, worked for a moment, now broken again

variable name should still be changed in the example

**Comment by netmindz** [comment] 2023-05-04 19:48
Think this new version is having mqtt issues. It says connected if I attach a onConnected method, but updates not coming into HA. Swapping back to 1.3.0 resolves the issue.

Is there a way to get debug logs from the library?

**Comment by dawidchyrzynski** [comment] 2024-02-05 19:26
@netmindz Closing this as I'm unable to reproduce the issue. You can enable the debug logs by uncommenting the `// #define ARDUINOHA_DEBUG` line in the `ArduinoHADefines.h` file.

**Closed by dawidchyrzynski** 2024-02-05 19:26 UTC

**Comment by Xieo** [comment] 2024-06-25 02:08
Hi Guys, I found out that when the options set as numbers     Dropdown.setOptions("0;1;2");

the code works and it calls the onSelectCommand().

but when set at text Dropdown.setOptions("Cool;Hot;Off");  it doesn't trigger the onSelectCommand()  and caused the mqtt to reset the connection.

any recommendation?
